config/routes.rb
Rails.application.routes.draw do
  root 'planets#index'
  resources :planets do
    resources :aliens, only: %i[new create destroy]
  end
end

app/models/alien.rb
class Alien < ApplicationRecord
  belongs_to :planet
  has_one_attached :photo
  validates :name, presence: true
  validates :age, presence: true

  def increment_age!
    self.age += 1
  end

  def self.oldest
    aliens = Alien.all.sort_by { |alien| alien.age }
    aliens.reverse
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :aliens
  has_one_attached :photo
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/aliens_controller.rb
class AliensController < ApplicationController
  # def index
  # end
  # def show
  # end

  def new
    @alien = Alien.new
    @planet = Planet.find(params[:planet_id])
  end

  def create
    @planet = Planet.find(params[:planet_id])
    @alien = Alien.new(alien_params)
    @alien.planet = @planet
    if @alien.save
      redirect_to @planet
    else
      render :new, status: :unprocessable_entity
    end
  end

  # def edit
  # end

  # def update
  # end

  def destroy
    @planet = Planet.find(params[:planet_id])
    @alien = Alien.find(params[:id])
    @alien.destroy
    redirect_to planet_path(@planet), status: :see_other
  end

  private

  def alien_params
    params.require(:alien).permit(:name, :age, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.all
  end

  def show
    @planet = Planet.find(params[:id])
  end

  def new
    @planet = Planet.new
  end

  def create
    @planet = Planet.new(planet_params)
    if @planet.save
      redirect_to planet_path(@planet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @planet = Planet.find(params[:id])
  end

  def update
    @planet = Planet.find(params[:id])
    if @planet.update(planet_params)
      redirect_to planet_path(@planet)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @planet = Planet.find(params[:id])
    @planet.destroy
    redirect_to planets_path, status: :see_other
  end

  private

  def planet_params
    params.require(:planet).permit(:name, :description, :photo)
  end
end

app/helpers/aliens_helper.rb
module AliensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/views/aliens/new.html.erb
<div class="container">
  <h1>Add an alien to <%= @planet.name %> planet</h1>
  <%= simple_form_for [@planet, @alien] do |f| %>
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.input :photo %>
    <%= f.submit class: 'mt-2' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/planets/edit.html.erb
<div class="container">
  <h1>Edit <%= @planet.name %></h1>
  <%= simple_form_for @planet do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.submit class: 'mt-2' %>
  <% end %>
</div>

app/views/planets/index.html.erb
<div class="container">
  <h1>Planets</h1>
  <% @planets.each do |planet| %>
    <%= cl_image_tag planet.photo.key, alt: "Planet picture" %>
    <p>
      <%= link_to planet.name, planet_path(planet) %>
    </p>
  <% end %>
  <%= link_to 'Add planet', new_planet_path %>
</div>

app/views/planets/new.html.erb
<div class="container">
  <h1>Create a planet</h1>
  <%= simple_form_for @planet do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :photo %>
    <%= f.submit class: 'mt-2' %>
  <% end %>
</div>

app/views/planets/show.html.erb
<div class="container">
  <h1><%= @planet.name %></h1>
  <%= cl_image_tag @planet.photo.key, alt: "Planet picture" %>
  <p><%= @planet.description %></p>
  <%= link_to 'Add alien', new_planet_alien_path(@planet) %>
  <%= link_to 'Edit planet', edit_planet_path %>
  <%= link_to 'Destroy planet', planet_path(@planet), data: {turbo_method: 'delete', turbo_confirm: 'Are you sure?'}  %>
  <h2>Aliens</h2>
  <% @planet.aliens.each do |alien| %>
    <%= cl_image_tag alien.photo.key, alt: "text" %>
    <p>Name: <%= alien.name %></p>
    <p>Age: <%= alien.age %></p>
    <p><%= link_to 'Destroy alien', [@planet, alien], data: {turbo_method: 'delete', data_confirm: 'Are you sure?'} %></p>
  <% end %>
</div>